@echo off
echo Stopping backend on 3001...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3001 ^| findstr LISTENING') do taskkill /F /PID %%a 2>nul
timeout /t 2 /nobreak >nul
cd /d %~dp0
echo Ensuring DB schema...
node scripts/fix-db.js
echo Generating Prisma client...
call npx prisma generate
echo Starting backend...
npm run dev
